### PR TITLE
Port to Polymer 2.0.

### PR DESCRIPTION
**Pull request by johnlim**
Hi @pkaske, 

Are you still to maintaining this component? I've ported it to Polymer 2.0 (CSS mixins doesn't seem to work now though - need to fix in a separate commit).

Regards,
John

### CODE REVIEW

**Comment by trading-peter** [comment]
Hi @johnlim,

I don't really use this component anymore. Thanks for your work, tho'  
Would you like to help maintain this component? I would add to the repo.

**Comment by johnlim** [comment]
@pkaske sure, I'll be happy to.

**Comment by trading-peter** [comment]
I added you to the repo. Feel free to merge this and to add yourself to the author section in the bower file.

Thanks for helping me out

**Comment by johnlim** [comment]
@pkaske Thanks for creating this in the first place. Will merge and please give feedback as and when you deem fit. :) Cheers.

**Pull request merged**
